import type { Metadata } from 'next';
import Link from 'next/link';

import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: 'flex', flexDirection: 'column' }}>
          <Link href="/">Home</Link>
          <Link href="/tear">Tear Test</Link>
          <Link href="/speed">Speed Test</Link>
        </nav>
        <main>
          <h1><span className={styles.mono}>useSyncExternalStore</span> vs. <span className={styles.mono}>useEffect</span></h1>
          {children}
        </main>
      </body>
    </html>
  );
}
